name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go !.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Checkout code 
      uses: actions/checkout@v2

    - name: Test
      run: make test
